/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class timing_rdtsc_Rdtsc */

#ifndef _Included_timing_rdtsc_Rdtsc
#define _Included_timing_rdtsc_Rdtsc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     timing_rdtsc_Rdtsc
 * Method:    get_rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_timing_Rdtsc_get_1rdtsc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
